"""add oauth_state to SlackIntegration

Revision ID: 73d9dec97606
Revises: b84ca0a78878
Create Date: 2025-04-27 22:23:15.754692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d9dec97606'
down_revision = 'b84ca0a78878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_state', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_integrations', schema=None) as batch_op:
        batch_op.drop_column('oauth_state')

    # ### end Alembic commands ###
