"""initial schema

Revision ID: b006c0ad86bb
Revises: 
Create Date: 2025-04-27 00:50:29.343321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b006c0ad86bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('ai_name', sa.String(length=80), nullable=True),
    sa.Column('ai_icon_url', sa.String(length=255), nullable=True),
    sa.Column('theme_color_header', sa.String(length=7), nullable=True),
    sa.Column('theme_color_user', sa.String(length=7), nullable=True),
    sa.Column('initial_message', sa.Text(), nullable=True),
    sa.Column('prompt_role', sa.Text(), nullable=True),
    sa.Column('prompt_task', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_history_user_id'), ['user_id'], unique=False)

    op.create_table('watched_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=128), nullable=False),
    sa.Column('channel_id', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('expiration_ms', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    with op.batch_alter_table('watched_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watched_sheets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watched_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watched_sheets_user_id'))

    op.drop_table('watched_sheets')
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_user_id'))

    op.drop_table('chat_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
