"""add SlackIntegration

Revision ID: b84ca0a78878
Revises: e5814279df60
Create Date: 2025-04-27 01:52:49.896309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84ca0a78878'
down_revision = 'e5814279df60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('client_secret', sa.String(length=256), nullable=False),
    sa.Column('bot_token', sa.String(length=256), nullable=True),
    sa.Column('team_id', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_integrations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_integrations_user_id'))

    op.drop_table('slack_integrations')
    # ### end Alembic commands ###
