"""add slack workspace

Revision ID: e5814279df60
Revises: b006c0ad86bb
Create Date: 2025-04-27 01:35:47.358267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5814279df60'
down_revision = 'b006c0ad86bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=True),
    sa.Column('bot_token', sa.String(length=256), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('installed_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['installed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    with op.batch_alter_table('slack_workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_workspaces_installed_by'), ['installed_by'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_client_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('slack_client_secret', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('slack_client_secret')
        batch_op.drop_column('slack_client_id')

    with op.batch_alter_table('slack_workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_workspaces_installed_by'))

    op.drop_table('slack_workspaces')
    # ### end Alembic commands ###
