"""Add ChatHistory table

Revision ID: 57a06407e7df
Revises: 
Create Date: 2025-04-20 18:23:23.347659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a06407e7df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('ai_name', sa.String(length=80), nullable=True),
    sa.Column('ai_icon_url', sa.String(length=255), nullable=True),
    sa.Column('theme_color_header', sa.String(length=7), nullable=True),
    sa.Column('theme_color_user', sa.String(length=7), nullable=True),
    sa.Column('initial_message', sa.Text(), nullable=True),
    sa.Column('prompt_role', sa.Text(), nullable=True),
    sa.Column('prompt_task', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('ai_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('ai_icon_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('theme_color_header', sa.VARCHAR(length=7), nullable=True),
    sa.Column('theme_color_user', sa.VARCHAR(length=7), nullable=True),
    sa.Column('initial_message', sa.TEXT(), nullable=True),
    sa.Column('prompt_role', sa.TEXT(), nullable=True),
    sa.Column('prompt_task', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_user_id'))

    op.drop_table('chat_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
