name: Build & Deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write       # OIDC で AWS ロールを引き受ける
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ECR_REPO: 904368995258.dkr.ecr.ap-northeast-1.amazonaws.com/chachat-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.13.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::904368995258:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build & push multi‑arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.ECR_REPO }}:latest
          cache-from: type=registry,ref=${{ env.ECR_REPO }}:buildcache
          cache-to:   type=registry,ref=${{ env.ECR_REPO }}:buildcache,mode=max,image-manifest=true

      - name: Run Alembic migrations on RDS
        run: |
          aws ecs run-task \
            --cluster aiqly-prod \
            --launch-type FARGATE \
            --task-definition aiqly-backend \
            --count 1 \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-032da3af4dc382e44,subnet-09512824c0aaea846,subnet-04a264dde050c95e5],securityGroups=[sg-049ab2067088e7119],assignPublicIp=DISABLED}" \
            --overrides '{"containerOverrides":[{"name":"backend","command":["flask","db","upgrade"]}],"cpu":"256","memory":"512"}' \
            --started-by github-ci

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster aiqly-prod \
            --service backend \
            --force-new-deployment